name: Python Linting

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pre-commit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Lint with Ruff
        run: |
          # Run Ruff linter
          ruff check .
          
      - name: Format with Ruff
        run: |
          # Run Ruff formatter (check only, don't modify files)
          ruff format --check .
          
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files 